import { useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'

type Transition = { id: string; row: number; col: number }
type Location = { id: string; name: string; x: number; y: number; size: number; background: string | null; transitions: Transition[] }
type ConnectorEndpoint = { locationId: string; transitionId: string }
type Connector = { id: string; from: ConnectorEndpoint; to: ConnectorEndpoint; color: string; arrows: 'none' | 'start' | 'end' | 'both' }

const GRID_COLS = 10, GRID_ROWS = 6, LOCATION_SIZE = 440
const CANVAS_WIDTH = 5000, CANVAS_HEIGHT = 3500, CONTENT_SCALE = 0.55
const LOCATION_SAFE_MARGIN = 34
const SNAP_SIZE = 32
function makeTransitions(locationId: string): Transition[] { return Array.from({ length: GRID_ROWS * GRID_COLS }, (_, index) => ({ id: `${locationId}-t-${index}`, row: Math.floor(index / GRID_COLS), col: index % GRID_COLS })) }
const initialLocations: Location[] = [
  { id: 'loc-1', name: 'Локация 1', x: 700, y: 500, size: LOCATION_SIZE, background: null, transitions: makeTransitions('loc-1') },
  { id: 'loc-2', name: 'Локация 2', x: 1450, y: 750, size: LOCATION_SIZE, background: null, transitions: makeTransitions('loc-2') },
]
const initialConnectors: Connector[] = [{ id: 'conn-1', from: { locationId: 'loc-1', transitionId: 'loc-1-t-25' }, to: { locationId: 'loc-2', transitionId: 'loc-2-t-34' }, color: '#aab4c4', arrows: 'both' }]
function transitionCenter(location: Location, transition: Transition) { const w = location.size / GRID_COLS, h = location.size / GRID_ROWS; return { x: location.x + transition.col * w + w / 2, y: location.y + transition.row * h + h / 2 } }

export function App() {
  const [mode, setMode] = useState<'viewer' | 'editor'>('editor'), [locations, setLocations] = useState(initialLocations), [connectors, setConnectors] = useState(initialConnectors)
  const [selected, setSelected] = useState<string | null>(null), [hoveredTransition, setHoveredTransition] = useState<ConnectorEndpoint | null>(null), [connectionStart, setConnectionStart] = useState<ConnectorEndpoint | null>(null), [zoom, setZoom] = useState(1), [snapToGrid, setSnapToGrid] = useState(true), [connectionMode, setConnectionMode] = useState(false)
  const dragging = useRef<{ id: string; startX: number; startY: number; x: number; y: number; size: number } | null>(null)
  const locationMap = useMemo(() => new Map(locations.map((item) => [item.id, item])), [locations])
  const connectedTransitions = useMemo(() => { const result = new Set<string>(); connectors.forEach((connector) => { result.add(`${connector.from.locationId}:${connector.from.transitionId}`); result.add(`${connector.to.locationId}:${connector.to.transitionId}`) }); return result }, [connectors])
  function addLocation() { const id = `loc-${Date.now()}`; setLocations((current) => [...current, { id, name: `Локация ${current.length + 1}`, x: 900 + current.length * 100, y: 1100 + current.length * 100, size: LOCATION_SIZE, background: null, transitions: makeTransitions(id) }]); setSelected(id) }
  function selectLocation(location: Location, event?: { stopPropagation: () => void }) { event?.stopPropagation(); setSelected(location.id) }
  function startDrag(event: ReactPointerEvent<SVGElement>, location: Location) { if (mode !== 'editor' || connectionMode) return; event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); dragging.current = { id: location.id, startX: event.clientX, startY: event.clientY, x: location.x, y: location.y, size: location.size }; setSelected(location.id) }
  function dragLocation(event: ReactPointerEvent<SVGElement>) { const drag = dragging.current; if (!drag) return; const dx = (event.clientX - drag.startX) / (zoom * CONTENT_SCALE), dy = (event.clientY - drag.startY) / (zoom * CONTENT_SCALE); let x = drag.x + dx, y = drag.y + dy; if (snapToGrid) { x = Math.round(x / SNAP_SIZE) * SNAP_SIZE; y = Math.round(y / SNAP_SIZE) * SNAP_SIZE } x = Math.max(LOCATION_SAFE_MARGIN, Math.min(CANVAS_WIDTH - drag.size - LOCATION_SAFE_MARGIN, x)); y = Math.max(LOCATION_SAFE_MARGIN, Math.min(CANVAS_HEIGHT - drag.size - LOCATION_SAFE_MARGIN, y)); setLocations((current) => current.map((item) => item.id === drag.id ? { ...item, x, y } : item)) }
  function stopDrag(event?: ReactPointerEvent<SVGElement>) { const drag = dragging.current; if (drag && event?.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); dragging.current = null }
  function beginConnection(endpoint: ConnectorEndpoint, event: ReactPointerEvent) { if (mode !== 'editor' || !connectionMode) return; event.stopPropagation(); setConnectionStart(endpoint); setSelected(endpoint.locationId) }
  function finishConnection(endpoint: ConnectorEndpoint, event: ReactPointerEvent) { if (!connectionStart || mode !== 'editor' || !connectionMode) return; event.stopPropagation(); if (connectionStart.locationId === endpoint.locationId && connectionStart.transitionId === endpoint.transitionId) return; setConnectors((current) => [...current, { id: `conn-${Date.now()}`, from: connectionStart, to: endpoint, color: '#aab4c4', arrows: 'both' }]); setConnectionStart(null) }
  function toggleConnectionMode() { setConnectionMode((value) => { const next = !value; if (!next) setConnectionStart(null); return next }) }
  function deleteSelected() { if (!selected || mode !== 'editor') return; setLocations((current) => current.filter((item) => item.id !== selected)); setConnectors((current) => current.filter((item) => item.from.locationId !== selected && item.to.locationId !== selected)); setConnectionStart(null); setSelected(null) }
  function setBackground(file: File | undefined) { if (!file || !selected) return; const reader = new FileReader(); reader.onload = () => setLocations((current) => current.map((item) => item.id === selected ? { ...item, background: String(reader.result) } : item)); reader.readAsDataURL(file) }
  function removeBackground() { if (!selected) return; setLocations((current) => current.map((item) => item.id === selected ? { ...item, background: null } : item)) }

  const titleScale = CONTENT_SCALE * zoom
  const titleFontSize = 18 / titleScale

  return <div className="app">
    <header className="topbar"><div className="brand">KARTA-CATWAR</div><div className="mode-switch"><button className={mode === 'viewer' ? 'active' : ''} onClick={() => { setMode('viewer'); setConnectionMode(false); setConnectionStart(null) }}>Просмотр</button><button className={mode === 'editor' ? 'active' : ''} onClick={() => setMode('editor')}>Редактор</button></div><div className="top-actions"><button onClick={() => setZoom((v) => Math.max(0.4, v - 0.1))}>−</button><span>{Math.round(zoom * 100)}%</span><button onClick={() => setZoom((v) => Math.min(2, v + 0.1))}>+</button></div></header>
    <aside className="toolbar"><button title="Выбор" className={!connectionMode ? 'active-tool' : ''} onClick={() => { setConnectionMode(false); setConnectionStart(null) }}>↖</button>{mode === 'editor' && <><button title="Привязка к сетке" className={snapToGrid ? 'active-tool' : ''} onClick={() => setSnapToGrid((v) => !v)}>▦</button><button title="Режим переходов" className={connectionMode ? 'active-tool' : ''} onClick={toggleConnectionMode}>↗</button><button title="Добавить локацию" onClick={addLocation}>＋</button><button title="Удалить выбранное" onClick={deleteSelected}>⌫</button></>}</aside>
    <main className="canvas-shell"><div className="canvas" onClick={(event) => { if (event.target === event.currentTarget) { setSelected(null); setConnectionStart(null) } }}><svg className="map" width={CANVAS_WIDTH} height={CANVAS_HEIGHT} viewBox={`0 0 ${CANVAS_WIDTH} ${CANVAS_HEIGHT}`} style={{ transform: `scale(${CONTENT_SCALE * zoom})` }}>
      <defs><pattern id="canvas-grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M 32 0 L 0 0 0 32" fill="none" stroke="#20252d" strokeWidth="1" /></pattern><marker id="arrow-end" markerWidth="14" markerHeight="14" refX="14" refY="7" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,0 L14,7 L0,14 Z" fill="context-stroke" /></marker><marker id="arrow-start" markerWidth="14" markerHeight="14" refX="0" refY="7" orient="auto" markerUnits="userSpaceOnUse"><path d="M14,0 L0,7 L14,14 Z" fill="context-stroke" /></marker></defs>
      <rect width={CANVAS_WIDTH} height={CANVAS_HEIGHT} fill="url(#canvas-grid)" />
      {locations.map((location) => <g key={location.id} className={`location ${selected === location.id ? 'selected' : ''}`} transform={`translate(${location.x} ${location.y})`}>
        <rect width={location.size} height={location.size} className="location-bg" onPointerDown={(e) => startDrag(e, location)} onPointerMove={dragLocation} onPointerUp={stopDrag} onPointerCancel={() => stopDrag()} onClick={(e) => selectLocation(location, e)} />
        {location.background && <image href={location.background} x="0" y="0" width={location.size} height={location.size} preserveAspectRatio="xMidYMid slice" pointerEvents="none" />}
        <rect x="0" y={-titleFontSize - 14} width={location.size} height={titleFontSize + 20} className="location-title-hitbox" onPointerDown={(e) => startDrag(e, location)} onPointerMove={dragLocation} onPointerUp={stopDrag} onPointerCancel={() => stopDrag()} onClick={(e) => selectLocation(location, e)} />
        <text x={location.size / 2} y="-14" textAnchor="middle" className="location-title" style={{ fontSize: titleFontSize }} pointerEvents="none">{location.name}</text>
        <g className="transition-grid" pointerEvents={connectionMode ? 'auto' : 'none'}>{location.transitions.map((transition) => { const w = location.size / GRID_COLS, h = location.size / GRID_ROWS, endpoint = { locationId: location.id, transitionId: transition.id }, key = `${location.id}:${transition.id}`, hovered = hoveredTransition?.locationId === location.id && hoveredTransition.transitionId === transition.id, start = connectionStart?.locationId === location.id && connectionStart.transitionId === transition.id, connected = connectedTransitions.has(key); return <g key={transition.id} className="transition-cell" onPointerEnter={() => setHoveredTransition(endpoint)} onPointerLeave={() => setHoveredTransition(null)} onPointerDown={(event) => { event.stopPropagation(); setSelected(location.id); if (connectionStart) finishConnection(endpoint, event); else beginConnection(endpoint, event) }} onClick={(event) => event.stopPropagation()}><rect x={transition.col * w} y={transition.row * h} width={w} height={h} style={{ fill: start ? '#ffffff38' : hovered && connectionMode ? '#ffffff24' : connected ? '#ffffff18' : 'transparent', stroke: start ? '#ffffff' : hovered && connectionMode ? '#dce4ef' : connected ? '#9eabbc' : '#3b424d', strokeWidth: start || (hovered && connectionMode) ? 2 : connected ? 1.5 : 1 }} /></g> })}</g>
        <rect width={location.size} height={location.size} className="location-frame" pointerEvents="none" />
      </g>)}
      <g className="connectors-layer">{connectors.map((connector) => { const fl = locationMap.get(connector.from.locationId), tl = locationMap.get(connector.to.locationId); if (!fl || !tl) return null; const ft = fl.transitions.find((i) => i.id === connector.from.transitionId), tt = tl.transitions.find((i) => i.id === connector.to.transitionId); if (!ft || !tt) return null; const a = transitionCenter(fl, ft), b = transitionCenter(tl, tt), midX = (a.x + b.x) / 2; return <path key={connector.id} d={`M ${a.x} ${a.y} C ${midX} ${a.y}, ${midX} ${b.y}, ${b.x} ${b.y}`} fill="none" stroke={connector.color} strokeWidth="4" markerStart={connector.arrows === 'start' || connector.arrows === 'both' ? 'url(#arrow-start)' : undefined} markerEnd={connector.arrows === 'end' || connector.arrows === 'both' ? 'url(#arrow-end)' : undefined} pointerEvents="none" /> })}</g>
      {connectionStart && hoveredTransition && (() => { const fl = locationMap.get(connectionStart.locationId), tl = locationMap.get(hoveredTransition.locationId); if (!fl || !tl) return null; const ft = fl.transitions.find((i) => i.id === connectionStart.transitionId), tt = tl.transitions.find((i) => i.id === hoveredTransition.transitionId); if (!ft || !tt) return null; const a = transitionCenter(fl, ft), b = transitionCenter(tl, tt); return <path className="connection-preview" d={`M ${a.x} ${a.y} C ${(a.x + b.x) / 2} ${a.y}, ${(a.x + b.x) / 2} ${b.y}, ${b.x} ${b.y}`} /> })()}
    </svg></div></main>
    {selected && mode === 'editor' && <section className="inspector"><div className="inspector-title">Локация</div><input value={locationMap.get(selected)?.name ?? ''} onChange={(event) => setLocations((current) => current.map((item) => item.id === selected ? { ...item, name: event.target.value } : item))} /><div className="inspector-field"><label>Фон локации</label><input type="file" accept="image/*" onChange={(event) => setBackground(event.target.files?.[0])} />{locationMap.get(selected)?.background && <button className="remove-bg" onClick={removeBackground}>Убрать фон</button>}</div><div className="inspector-note">Фон находится под сеткой переходов.</div></section>}
  </div>
}