import { useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'

type Transition = { id: string; row: number; col: number }
type Point = { x: number; y: number }
type Location = { id: string; name: string; x: number; y: number; size: number; background: string | null; transitions: Transition[] }
type ConnectorEndpoint = { locationId: string; transitionId: string }
type ConnectionSide = 'left' | 'right' | 'top' | 'bottom'
type Connector = { id: string; from: ConnectorEndpoint; to: ConnectorEndpoint; color: string; arrows: 'none' | 'start' | 'end' | 'both'; oneWay?: boolean; bends?: Point[]; fromSide?: ConnectionSide; toSide?: ConnectionSide }

const GRID_COLS = 10, GRID_ROWS = 6, LOCATION_SIZE = 440
const CANVAS_WIDTH = 5000, CANVAS_HEIGHT = 3500, CONTENT_SCALE = 0.55
const LOCATION_SAFE_MARGIN = 34, SNAP_SIZE = 32
function makeTransitions(locationId: string): Transition[] { return Array.from({ length: GRID_ROWS * GRID_COLS }, (_, index) => ({ id: `${locationId}-t-${index}`, row: Math.floor(index / GRID_COLS), col: index % GRID_COLS })) }
const initialLocations: Location[] = [
  { id: 'loc-1', name: 'Локация 1', x: 700, y: 500, size: LOCATION_SIZE, background: null, transitions: makeTransitions('loc-1') },
  { id: 'loc-2', name: 'Локация 2', x: 1450, y: 750, size: LOCATION_SIZE, background: null, transitions: makeTransitions('loc-2') },
]
const initialConnectors: Connector[] = [{ id: 'conn-1', from: { locationId: 'loc-1', transitionId: 'loc-1-t-25' }, to: { locationId: 'loc-2', transitionId: 'loc-2-t-34' }, color: '#ffffff', arrows: 'none' }]
function transitionCenter(location: Location, transition: Transition): Point { const w = location.size / GRID_COLS, h = location.size / GRID_ROWS; return { x: location.x + transition.col * w + w / 2, y: location.y + transition.row * h + h / 2 } }
function connectionSide(location: Location, other: Location): ConnectionSide { const dx = other.x + other.size / 2 - (location.x + location.size / 2), dy = other.y + other.size / 2 - (location.y + location.size / 2); if (Math.abs(dx) >= Math.abs(dy)) return dx >= 0 ? 'right' : 'left'; return dy >= 0 ? 'bottom' : 'top' }
function endpointSide(location: Location, transition: Transition, other: Point, fallback: ConnectionSide): ConnectionSide { const center = transitionCenter(location, transition), dx = other.x - center.x, dy = other.y - center.y; if (Math.abs(dx) < 1 && Math.abs(dy) < 1) return fallback; return Math.abs(dx) >= Math.abs(dy) ? (dx >= 0 ? 'right' : 'left') : (dy >= 0 ? 'bottom' : 'top') }
function transitionEdgePoint(location: Location, transition: Transition, side: ConnectionSide): Point { const center = transitionCenter(location, transition), w = location.size / GRID_COLS, h = location.size / GRID_ROWS; if (side === 'left') return { x: center.x - w / 2, y: center.y }; if (side === 'right') return { x: center.x + w / 2, y: center.y }; if (side === 'top') return { x: center.x, y: center.y - h / 2 }; return { x: center.x, y: center.y + h / 2 } }
function locationBoundaryPoint(location: Location, from: Point): Point { const left = location.x, right = location.x + location.size, top = location.y, bottom = location.y + location.size, clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value)); const points = [{ x: left, y: clamp(from.y, top, bottom), distance: Math.abs(from.x - left) }, { x: right, y: clamp(from.y, top, bottom), distance: Math.abs(from.x - right) }, { x: clamp(from.x, left, right), y: top, distance: Math.abs(from.y - top) }, { x: clamp(from.x, left, right), y: bottom, distance: Math.abs(from.y - bottom) }]; return points.reduce((best, point) => point.distance < best.distance ? point : best, points[0]) }
function defaultConnectorPoints(a: Point, b: Point, sourceSide: ConnectionSide): Point[] { if (sourceSide === 'left' || sourceSide === 'right') { const midX = a.x + (b.x - a.x) / 2; return [a, { x: midX, y: a.y }, { x: midX, y: b.y }, b] } const midY = a.y + (b.y - a.y) / 2; return [a, { x: a.x, y: midY }, { x: b.x, y: midY }, b] }
function orthogonalPoints(a: Point, b: Point, sourceSide: ConnectionSide, bends?: Point[]): Point[] { if (!bends?.length) return defaultConnectorPoints(a, b, sourceSide); const anchors = [a, ...bends, b], result: Point[] = [a]; anchors.slice(1).forEach((point, index) => { const previous = result[result.length - 1], dx = point.x - previous.x, dy = point.y - previous.y; if (Math.abs(dx) < 0.5 || Math.abs(dy) < 0.5) result.push(point); else { const horizontalFirst = index === 0 ? (sourceSide === 'left' || sourceSide === 'right') : Math.abs(dx) >= Math.abs(dy); result.push(horizontalFirst ? { x: point.x, y: previous.y } : { x: previous.x, y: point.y }); result.push(point) } }); return result }
function pathFromPoints(points: Point[]) { return points.map((point, index) => `${index === 0 ? 'M' : 'L'} ${point.x} ${point.y}`).join(' ') }
function samePoint(a: Point, b: Point, tolerance = 6) { return Math.hypot(a.x - b.x, a.y - b.y) <= tolerance }
function isCollinearBetween(a: Point, p: Point, b: Point) { const cross = Math.abs((p.x - a.x) * (b.y - a.y) - (p.y - a.y) * (b.x - a.x)), tolerance = 8; return cross <= tolerance * Math.max(1, Math.hypot(b.x - a.x, b.y - a.y)) && p.x >= Math.min(a.x, b.x) - tolerance && p.x <= Math.max(a.x, b.x) + tolerance && p.y >= Math.min(a.y, b.y) - tolerance && p.y <= Math.max(a.y, b.y) + tolerance }
function normalizeRoute(points: Point[]): Point[] { const deduped: Point[] = []; points.forEach((point) => { if (!deduped.length || !samePoint(deduped[deduped.length - 1], point)) deduped.push(point) }); const result: Point[] = []; deduped.forEach((point, index) => { if (index > 0 && index < deduped.length - 1 && isCollinearBetween(deduped[index - 1], point, deduped[index + 1])) return; result.push(point) }); return result }
function sideHandlePoint(location: Location, transition: Transition | undefined, side: ConnectionSide): Point { if (!transition) return { x: location.x + location.size / 2, y: location.y + location.size / 2 }; const center = transitionCenter(location, transition), w = location.size / GRID_COLS, h = location.size / GRID_ROWS; if (side === 'left') return { x: center.x - w / 2, y: center.y }; if (side === 'right') return { x: center.x + w / 2, y: center.y }; if (side === 'top') return { x: center.x, y: center.y - h / 2 }; return { x: center.x, y: center.y + h / 2 } }

export function App() {
  const [mode, setMode] = useState<'viewer' | 'editor'>('editor'), [locations, setLocations] = useState(initialLocations), [connectors, setConnectors] = useState(initialConnectors)
  const [selected, setSelected] = useState<string | null>(null), [selectedConnectorId, setSelectedConnectorId] = useState<string | null>(null), [hoveredTransition, setHoveredTransition] = useState<ConnectorEndpoint | null>(null), [hoveredLocationId, setHoveredLocationId] = useState<string | null>(null), [connectionStart, setConnectionStart] = useState<ConnectorEndpoint | null>(null), [zoom, setZoom] = useState(1), [snapToGrid, setSnapToGrid] = useState(true), [connectionMode, setConnectionMode] = useState(false), [deleteConnectionMode, setDeleteConnectionMode] = useState(false), [oneWayMode, setOneWayMode] = useState(false), [panMode, setPanMode] = useState(false)
  const dragging = useRef<{ id: string; startX: number; startY: number; x: number; y: number; size: number } | null>(null)
  const panning = useRef<{ startX: number; startY: number; scrollLeft: number; scrollTop: number } | null>(null)
  const midDragging = useRef<{ connectorId: string; segmentIndex: number; points: Point[] } | null>(null)
  const endpointDragging = useRef<{ connectorId: string; endpoint: 'from' | 'to' } | null>(null)
  const canvasShellRef = useRef<HTMLElement | null>(null)
  const locationMap = useMemo(() => new Map(locations.map((item) => [item.id, item])), [locations])
  const connectedTransitions = useMemo(() => { const result = new Set<string>(); connectors.forEach((connector) => { result.add(`${connector.from.locationId}:${connector.from.transitionId}`); if (!connector.oneWay) result.add(`${connector.to.locationId}:${connector.to.transitionId}`) }); return result }, [connectors])
  const oneWayTransitions = useMemo(() => { const result = new Set<string>(); connectors.forEach((connector) => { if (connector.oneWay) result.add(`${connector.from.locationId}:${connector.from.transitionId}`) }); return result }, [connectors])
  function addLocation() { const id = `loc-${Date.now()}`; setLocations((current) => [...current, { id, name: `Локация ${current.length + 1}`, x: 900 + current.length * 100, y: 1100 + current.length * 100, size: LOCATION_SIZE, background: null, transitions: makeTransitions(id) }]); setSelected(id) }
  function selectLocation(location: Location, event?: { stopPropagation: () => void }) { event?.stopPropagation(); setSelected(location.id) }
  function startDrag(event: ReactPointerEvent<SVGElement>, location: Location) { if (mode !== 'editor' || connectionMode || panMode) return; event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); dragging.current = { id: location.id, startX: event.clientX, startY: event.clientY, x: location.x, y: location.y, size: location.size }; setSelected(location.id) }
  function startTitleDrag(event: ReactPointerEvent<SVGElement>, location: Location) { if (mode !== 'editor' || panMode) return; event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); dragging.current = { id: location.id, startX: event.clientX, startY: event.clientY, x: location.x, y: location.y, size: location.size }; setSelected(location.id) }
  function dragLocation(event: ReactPointerEvent<SVGElement>) { const drag = dragging.current; if (!drag) return; const dx = (event.clientX - drag.startX) / (zoom * CONTENT_SCALE), dy = (event.clientY - drag.startY) / (zoom * CONTENT_SCALE); let x = drag.x + dx, y = drag.y + dy; if (snapToGrid) { x = Math.round(x / SNAP_SIZE) * SNAP_SIZE; y = Math.round(y / SNAP_SIZE) * SNAP_SIZE } x = Math.max(LOCATION_SAFE_MARGIN, Math.min(CANVAS_WIDTH - drag.size - LOCATION_SAFE_MARGIN, x)); y = Math.max(LOCATION_SAFE_MARGIN, Math.min(CANVAS_HEIGHT - drag.size - LOCATION_SAFE_MARGIN, y)); setLocations((current) => current.map((item) => item.id === drag.id ? { ...item, x, y } : item)) }
  function stopDrag(event?: ReactPointerEvent<SVGElement>) { const drag = dragging.current; if (drag && event && event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); dragging.current = null }
  function beginPan(event: ReactPointerEvent<HTMLElement>) { if (!panMode || event.button !== 0) return; const shell = canvasShellRef.current; if (!shell) return; event.preventDefault(); panning.current = { startX: event.clientX, startY: event.clientY, scrollLeft: shell.scrollLeft, scrollTop: shell.scrollTop }; shell.setPointerCapture(event.pointerId) }
  function movePan(event: ReactPointerEvent<HTMLElement>) { const pan = panning.current, shell = canvasShellRef.current; if (!pan || !shell) return; shell.scrollLeft = pan.scrollLeft - (event.clientX - pan.startX); shell.scrollTop = pan.scrollTop - (event.clientY - pan.startY) }
  function stopPan(event?: ReactPointerEvent<HTMLElement>) { const shell = canvasShellRef.current; if (shell && event && shell.hasPointerCapture(event.pointerId)) shell.releasePointerCapture(event.pointerId); panning.current = null }
  function beginConnection(endpoint: ConnectorEndpoint, event: ReactPointerEvent) { if (mode !== 'editor' || !connectionMode || deleteConnectionMode || oneWayMode) return; event.stopPropagation(); setConnectionStart(endpoint); setSelected(endpoint.locationId) }
  function beginOneWayConnection(endpoint: ConnectorEndpoint, event: ReactPointerEvent) { if (mode !== 'editor' || !connectionMode || !oneWayMode || deleteConnectionMode || connectionStart) return; event.stopPropagation(); setConnectionStart(endpoint); setSelected(endpoint.locationId) }
  function finishConnection(endpoint: ConnectorEndpoint, event: ReactPointerEvent) { if (!connectionStart || !connectionMode || deleteConnectionMode || oneWayMode) return; event.stopPropagation(); if (connectionStart.locationId === endpoint.locationId && connectionStart.transitionId === endpoint.transitionId) return; setConnectors((current) => [...current, { id: `conn-${Date.now()}`, from: connectionStart, to: endpoint, color: '#ffffff', arrows: 'none', oneWay: false }]); setConnectionStart(null) }
  function finishOneWayConnection(location: Location, event: ReactPointerEvent<SVGElement>) { if (!connectionStart || !connectionMode || !oneWayMode || deleteConnectionMode || connectionStart.locationId === location.id) return; event.stopPropagation(); setConnectors((current) => [...current, { id: `conn-${Date.now()}`, from: connectionStart, to: { locationId: location.id, transitionId: '__location__' }, color: '#FF7000', arrows: 'none', oneWay: true }]); setConnectionStart(null); setHoveredTransition(null); setHoveredLocationId(null) }
  function deleteTransition(endpoint: ConnectorEndpoint, event: ReactPointerEvent) { if (mode !== 'editor' || !connectionMode || !deleteConnectionMode) return; event.stopPropagation(); setConnectors((current) => current.filter((connector) => !(connector.from.locationId === endpoint.locationId && connector.from.transitionId === endpoint.transitionId) && !(connector.to.locationId === endpoint.locationId && connector.to.transitionId === endpoint.transitionId))); setConnectionStart(null) }
  function toggleConnectionMode() { setConnectionMode((value) => { const next = !value; if (!next) { setConnectionStart(null); setDeleteConnectionMode(false); setOneWayMode(false) } return next }) }
  function toggleOneWayMode() { setOneWayMode((value) => !value); setDeleteConnectionMode(false); setConnectionStart(null); setHoveredLocationId(null) }
  function deleteSelected() { if (!selected || mode !== 'editor') return; setLocations((current) => current.filter((item) => item.id !== selected)); setConnectors((current) => current.filter((item) => item.from.locationId !== selected && item.to.locationId !== selected)); setConnectionStart(null); setSelected(null); setSelectedConnectorId(null) }
  function setBackground(file: File | undefined) { if (!file || !selected) return; const reader = new FileReader(); reader.onload = () => setLocations((current) => current.map((item) => item.id === selected ? { ...item, background: String(reader.result) } : item)); reader.readAsDataURL(file) }
  function removeBackground() { if (!selected) return; setLocations((current) => current.map((item) => item.id === selected ? { ...item, background: null } : item)) }
  function svgPoint(event: ReactPointerEvent<SVGElement>): Point { const svg = event.currentTarget.ownerSVGElement, rect = svg?.getBoundingClientRect(), scale = CONTENT_SCALE * zoom; return rect ? { x: (event.clientX - rect.left) / scale, y: (event.clientY - rect.top) / scale } : { x: 0, y: 0 } }
  function connectorGeometry(connector: Connector) { const fl = locationMap.get(connector.from.locationId), tl = locationMap.get(connector.to.locationId); if (!fl || !tl) return null; const ft = fl.transitions.find((item) => item.id === connector.from.transitionId); if (!ft) return null; const tc = tl.transitions.find((item) => item.id === connector.to.transitionId); const targetCenter = connector.oneWay ? { x: tl.x + tl.size / 2, y: tl.y + tl.size / 2 } : tc ? transitionCenter(tl, tc) : { x: tl.x + tl.size / 2, y: tl.y + tl.size / 2 }; const sourceSide = connector.fromSide ?? endpointSide(fl, ft, targetCenter, connectionSide(fl, tl)); const targetSide = connector.oneWay ? connectionSide(tl, fl) : connector.toSide ?? (tc ? endpointSide(tl, tc, transitionCenter(fl, ft), connectionSide(tl, fl)) : connectionSide(tl, fl)); const a = transitionEdgePoint(fl, ft, sourceSide), b = connector.oneWay ? locationBoundaryPoint(tl, a) : tc ? transitionEdgePoint(tl, tc, targetSide) : a; return { fl, tl, ft, tc, sourceSide, targetSide, a, b } }
  function beginMidDrag(event: ReactPointerEvent<SVGCircleElement>, connectorId: string, segmentIndex: number) { if (mode !== 'editor' || connectionMode || panMode || deleteConnectionMode) return; event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); const connector = connectors.find((item) => item.id === connectorId), geometry = connector ? connectorGeometry(connector) : null; if (!geometry) return; midDragging.current = { connectorId, segmentIndex, points: orthogonalPoints(geometry.a, geometry.b, geometry.sourceSide, connector?.bends) }; setSelectedConnectorId(connectorId) }
  function dragMid(event: ReactPointerEvent<SVGCircleElement>) { const drag = midDragging.current; if (!drag) return; const start = drag.points[drag.segmentIndex], end = drag.points[drag.segmentIndex + 1]; if (!start || !end) return; const pointer = svgPoint(event), horizontal = Math.abs(end.x - start.x) >= Math.abs(end.y - start.y); const next = drag.points.map((point) => ({ ...point })); if (horizontal) { const y = pointer.y; if (drag.segmentIndex > 0) next[drag.segmentIndex].y = y; if (drag.segmentIndex < next.length - 1) next[drag.segmentIndex + 1].y = y } else { const x = pointer.x; if (drag.segmentIndex > 0) next[drag.segmentIndex].x = x; if (drag.segmentIndex < next.length - 1) next[drag.segmentIndex + 1].x = x } const nextPoints = normalizeRoute(next); const connector = connectors.find((item) => item.id === drag.connectorId), geometry = connector ? connectorGeometry(connector) : null; const defaults = geometry ? defaultConnectorPoints(geometry.a, geometry.b, geometry.sourceSide) : null; const reset = !!defaults && nextPoints.length === defaults.length && nextPoints.every((point, index) => samePoint(point, defaults[index], 8)); setConnectors((current) => current.map((item) => item.id === drag.connectorId ? { ...item, bends: reset ? undefined : nextPoints.slice(1, -1) } : item)) }
  function stopMidDrag(event?: ReactPointerEvent<SVGCircleElement>) { if (event && event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); midDragging.current = null }
  function beginEndpointDrag(event: ReactPointerEvent<SVGCircleElement>, connectorId: string, endpoint: 'from' | 'to') { if (mode !== 'editor' || connectionMode || panMode || deleteConnectionMode) return; event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); endpointDragging.current = { connectorId, endpoint }; setSelectedConnectorId(connectorId) }
  function dragEndpoint(event: ReactPointerEvent<SVGCircleElement>) { const drag = endpointDragging.current; if (!drag) return; const connector = connectors.find((item) => item.id === drag.connectorId); if (!connector) return; const geometry = connectorGeometry(connector); if (!geometry) return; const location = drag.endpoint === 'from' ? geometry.fl : geometry.tl, transition = drag.endpoint === 'from' ? geometry.ft : geometry.tc; if (!transition) return; const pointer = svgPoint(event), center = transitionCenter(location, transition), dx = pointer.x - center.x, dy = pointer.y - center.y; const side: ConnectionSide = Math.abs(dx) >= Math.abs(dy) ? (dx >= 0 ? 'right' : 'left') : (dy >= 0 ? 'bottom' : 'top'); setConnectors((current) => current.map((item) => item.id === drag.connectorId ? { ...item, [drag.endpoint === 'from' ? 'fromSide' : 'toSide']: side, bends: undefined } : item)) }
  function stopEndpointDrag(event?: ReactPointerEvent<SVGCircleElement>) { if (event && event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); endpointDragging.current = null }
  const titleFontSize = 50, titleHitboxMargin = 16

  return <div className="app">
    <header className="topbar"><div className="brand">KARTA-CATWAR</div><div className="mode-switch"><button className={mode === 'viewer' ? 'active' : ''} onClick={() => { setMode('viewer'); setConnectionMode(false); setDeleteConnectionMode(false); setOneWayMode(false); setConnectionStart(null); setSelectedConnectorId(null) }}>Просмотр</button><button className={mode === 'editor' ? 'active' : ''} onClick={() => setMode('editor')}>Редактор</button></div><div className="top-actions"><button onClick={() => setZoom((v) => Math.max(0.4, v - 0.1))}>−</button><span>{Math.round(zoom * 100)}%</span><button onClick={() => setZoom((v) => Math.min(2, v + 0.1))}>+</button></div></header>
    <aside className="toolbar">
      <button title="Выбор" className={!panMode && !connectionMode ? 'active-tool' : ''} onClick={() => { setPanMode(false); setConnectionMode(false); setDeleteConnectionMode(false); setOneWayMode(false); setConnectionStart(null); setSelectedConnectorId(null) }}><img src="/KARTA-CATWAR/icons/cursor.svg" alt="" /></button>
      <button title="Перемещение по холсту" className={panMode ? 'active-tool' : ''} onClick={() => { setPanMode((value) => !value); setConnectionStart(null); setSelectedConnectorId(null) }}><img src="/KARTA-CATWAR/icons/holding-hand.svg" alt="" /></button>
      {mode === 'editor' && <><button title="Привязка к сетке" className={snapToGrid ? 'active-tool' : ''} onClick={() => setSnapToGrid((v) => !v)}><img src="/KARTA-CATWAR/icons/grid.svg" alt="" /></button><button title="Режим переходов" className={connectionMode ? 'active-tool' : ''} onClick={toggleConnectionMode}><img src="/KARTA-CATWAR/icons/arrow.svg" alt="" /></button><button title="Добавить локацию" onClick={addLocation}><img src="/KARTA-CATWAR/icons/add-location.svg" alt="" /></button><button title="Удалить выбранное" onClick={deleteSelected}><img src="/KARTA-CATWAR/icons/delete-location.svg" alt="" /></button></>}
    </aside>
    {mode === 'editor' && connectionMode && <aside className="transition-tools"><button title="Переход в одну сторону" className={oneWayMode ? 'active-tool' : ''} onClick={toggleOneWayMode}><img src="/KARTA-CATWAR/icons/arrow.svg" alt="" /></button><button title="Удаление переходов" className={deleteConnectionMode ? 'active-tool' : ''} onClick={() => { setDeleteConnectionMode((value) => !value); setOneWayMode(false); setConnectionStart(null); setHoveredLocationId(null) }}><img src="/KARTA-CATWAR/icons/delete-location.svg" alt="" /></button></aside>}
    <main ref={canvasShellRef} className={`canvas-shell ${panMode ? 'pan-mode' : ''}`} onPointerDown={beginPan} onPointerMove={movePan} onPointerUp={stopPan} onPointerCancel={stopPan}>
      <div className="canvas" onClick={(event) => { if (event.target === event.currentTarget && !panMode) { setSelected(null); setConnectionStart(null); setSelectedConnectorId(null) } }}>
        <svg className="map" width={CANVAS_WIDTH} height={CANVAS_HEIGHT} viewBox={`0 0 ${CANVAS_WIDTH} ${CANVAS_HEIGHT}`} style={{ transform: `scale(${CONTENT_SCALE * zoom})` }}>
          <defs><pattern id="canvas-grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M 32 0 L 0 0 0 32" fill="none" stroke="#20252d" strokeWidth="1" /></pattern></defs>
          <rect width={CANVAS_WIDTH} height={CANVAS_HEIGHT} fill="url(#canvas-grid)" />
          {locations.map((location) => <g key={location.id} className={`location ${selected === location.id ? 'selected' : ''}`} transform={`translate(${location.x} ${location.y})`}>
            <rect width={location.size} height={location.size} className="location-bg" onPointerDown={(e) => { if (connectionStart && oneWayMode) finishOneWayConnection(location, e); else startDrag(e, location) }} onPointerMove={dragLocation} onPointerUp={stopDrag} onPointerCancel={() => stopDrag()} onClick={(e) => selectLocation(location, e)} onPointerEnter={() => setHoveredLocationId(location.id)} onPointerLeave={() => setHoveredLocationId(null)} />
            {location.background && <image href={location.background} x="0" y="0" width={location.size} height={location.size} preserveAspectRatio="xMidYMid slice" pointerEvents="none" />}
            <rect x={-titleHitboxMargin} y={-titleFontSize - titleHitboxMargin} width={location.size + titleHitboxMargin * 2} height={titleFontSize + titleHitboxMargin + 20} className="location-title-hitbox" onPointerDown={(e) => startTitleDrag(e, location)} onPointerMove={dragLocation} onPointerUp={stopDrag} onPointerCancel={() => stopDrag()} onClick={(e) => selectLocation(location, e)} />
            <text x={location.size / 2} y="-14" textAnchor="middle" className="location-title" style={{ fontSize: titleFontSize }} pointerEvents="none">{location.name}</text>
            <g className="transition-grid" pointerEvents={connectionMode && !(oneWayMode && connectionStart) ? 'auto' : 'none'}>{location.transitions.map((transition) => { const w = location.size / GRID_COLS, h = location.size / GRID_ROWS, endpoint = { locationId: location.id, transitionId: transition.id }, key = `${location.id}:${transition.id}`, start = connectionStart?.locationId === location.id && connectionStart.transitionId === transition.id, connected = connectedTransitions.has(key), oneWayConnected = oneWayTransitions.has(key); return <g key={transition.id} className="transition-cell" onPointerEnter={() => setHoveredTransition(endpoint)} onPointerLeave={() => setHoveredTransition(null)} onPointerDown={(event) => { event.stopPropagation(); setSelected(location.id); if (deleteConnectionMode) deleteTransition(endpoint, event); else if (connectionStart) finishConnection(endpoint, event); else if (oneWayMode) beginOneWayConnection(endpoint, event); else beginConnection(endpoint, event) }} onClick={(event) => event.stopPropagation()}><rect x={transition.col * w} y={transition.row * h} width={w} height={h} style={{ fill: start ? (oneWayMode ? '#FF7000' : '#ffffff38') : oneWayConnected ? '#FF7000' : connected ? '#ffffff' : 'transparent', stroke: oneWayConnected || (start && oneWayMode) ? '#FF7000' : 'rgba(255, 255, 255, .15)', strokeWidth: 2 }} /></g> })}</g>
            <rect width={location.size} height={location.size} className="location-frame" pointerEvents="none" />
          </g>)}
          <g className="connectors-layer">{connectors.map((connector) => { const geometry = connectorGeometry(connector); if (!geometry) return null; const { a, b, sourceSide } = geometry, points = orthogonalPoints(a, b, sourceSide, connector.bends), d = pathFromPoints(points), editable = mode === 'editor' && selectedConnectorId === connector.id, segmentHandles = points.slice(0, -1).map((point, index) => ({ point: { x: (point.x + points[index + 1].x) / 2, y: (point.y + points[index + 1].y) / 2 }, index })), sides: ConnectionSide[] = ['left', 'right', 'top', 'bottom']; return <g key={connector.id}>
            <path d={d} fill="none" stroke="transparent" strokeWidth="22" pointerEvents="stroke" onPointerDown={(event) => { if (connectionMode || panMode || deleteConnectionMode) return; event.stopPropagation(); setSelectedConnectorId(connector.id) }} />
            {connector.oneWay ? <path d={d} fill="none" stroke="#FF7000" strokeWidth="4" strokeDasharray="10 8" strokeLinecap="butt" strokeLinejoin="miter" pointerEvents="none" /> : <><path d={d} fill="none" stroke="#000000" strokeWidth="7" strokeLinecap="butt" strokeLinejoin="miter" pointerEvents="none" /><path d={d} fill="none" stroke="#ffffff" strokeWidth="4" strokeLinecap="butt" strokeLinejoin="miter" pointerEvents="none" /></>}
            {editable && <>{segmentHandles.map(({ point, index }) => <circle key={`mid-${index}`} className="connector-mid-handle" cx={point.x} cy={point.y} r="8" onPointerDown={(event) => beginMidDrag(event, connector.id, index)} onPointerMove={dragMid} onPointerUp={stopMidDrag} onPointerCancel={() => stopMidDrag()} />)}
              {sides.map((side) => { const point = sideHandlePoint(geometry.fl, geometry.ft, side); return <g key={`from-${side}`} className="connector-side-handle-group"><circle cx={point.x} cy={point.y} r="18" fill="transparent" pointerEvents="all" onPointerDown={(event) => beginEndpointDrag(event, connector.id, 'from')} onPointerMove={dragEndpoint} onPointerUp={stopEndpointDrag} onPointerCancel={() => stopEndpointDrag()} /><circle className={`connector-side-handle ${connector.fromSide === side ? 'active' : ''}`} cx={point.x} cy={point.y} r="10" pointerEvents="none" /></g> })}
              {!connector.oneWay && geometry.tc && sides.map((side) => { const point = sideHandlePoint(geometry.tl, geometry.tc, side); return <g key={`to-${side}`} className="connector-side-handle-group"><circle cx={point.x} cy={point.y} r="18" fill="transparent" pointerEvents="all" onPointerDown={(event) => beginEndpointDrag(event, connector.id, 'to')} onPointerMove={dragEndpoint} onPointerUp={stopEndpointDrag} onPointerCancel={() => stopEndpointDrag()} /><circle className={`connector-side-handle ${connector.toSide === side ? 'active' : ''}`} cx={point.x} cy={point.y} r="10" pointerEvents="none" /></g> })}
            </>}
          </g> })}</g>
          {connectionStart && !deleteConnectionMode && !oneWayMode && hoveredTransition && (() => { const fl = locationMap.get(connectionStart.locationId), tl = locationMap.get(hoveredTransition.locationId); if (!fl || !tl) return null; const ft = fl.transitions.find((i) => i.id === connectionStart.transitionId), tt = tl.transitions.find((i) => i.id === hoveredTransition.transitionId); if (!ft || !tt) return null; const sourceSide = endpointSide(fl, ft, transitionCenter(tl, tt), connectionSide(fl, tl)), targetSide = endpointSide(tl, tt, transitionCenter(fl, ft), connectionSide(tl, fl)), a = transitionEdgePoint(fl, ft, sourceSide), b = transitionEdgePoint(tl, tt, targetSide), d = pathFromPoints(defaultConnectorPoints(a, b, sourceSide)); return <g><path d={d} fill="none" stroke="#000000" strokeWidth="7" strokeLinecap="butt" strokeLinejoin="miter" /><path className="connection-preview" d={d} stroke="#ffffff" strokeWidth="4" strokeLinecap="butt" strokeLinejoin="miter" fill="none" /></g> })()}
          {connectionStart && oneWayMode && !deleteConnectionMode && hoveredLocationId && (() => { const fl = locationMap.get(connectionStart.locationId), tl = locationMap.get(hoveredLocationId); if (!fl || !tl || fl.id === tl.id) return null; const ft = fl.transitions.find((i) => i.id === connectionStart.transitionId); if (!ft) return null; const sourceSide = endpointSide(fl, ft, { x: tl.x + tl.size / 2, y: tl.y + tl.size / 2 }, connectionSide(fl, tl)), a = transitionEdgePoint(fl, ft, sourceSide), b = locationBoundaryPoint(tl, a), d = pathFromPoints(defaultConnectorPoints(a, b, sourceSide)); return <path key="one-way-preview" d={d} fill="none" stroke="#FF7000" strokeWidth="4" strokeDasharray="10 8" strokeLinecap="butt" strokeLinejoin="miter" pointerEvents="none" /> })()}
        </svg>
      </div>
    </main>
    {selected && mode === 'editor' && <section className="inspector"><div className="inspector-title">Локация</div><input value={locationMap.get(selected)?.name ?? ''} onChange={(event) => setLocations((current) => current.map((item) => item.id === selected ? { ...item, name: event.target.value } : item))} /><div className="inspector-field"><label>Фон локации</label><input type="file" accept="image/*" onChange={(event) => setBackground(event.target.files?.[0])} />{locationMap.get(selected)?.background && <button className="remove-bg" onClick={removeBackground}>Убрать фон</button>}</div><div className="inspector-note">Фон находится под сеткой переходов.</div></section>}
  </div>
}