import { useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'

type Transition = { id:string; row:number; col:number }
type Point = { x:number; y:number }
type Location = { id:string; name:string; x:number; y:number; size:number; background:string|null; transitions:Transition[] }
type Endpoint = { locationId:string; transitionId:string }
type Side = 'left'|'right'|'top'|'bottom'
type Connector = { id:string; from:Endpoint; to:Endpoint; color:string; arrows:'none'|'start'|'end'|'both'; oneWay?:boolean; bends?:Point[]; fromSide?:Side; toSide?:Side }

const COLS=10, ROWS=6, SIZE=440, CW=5000, CH=3500, SCALE=.55, SNAP=32, MAGNET=64
const makeTransitions=(id:string):Transition[]=>Array.from({length:ROWS*COLS},(_,i)=>({id:`${id}-t-${i}`,row:Math.floor(i/COLS),col:i%COLS}))
const initialLocations:Location[]=[
 {id:'loc-1',name:'Локация 1',x:700,y:500,size:SIZE,background:null,transitions:makeTransitions('loc-1')},
 {id:'loc-2',name:'Локация 2',x:1450,y:750,size:SIZE,background:null,transitions:makeTransitions('loc-2')}
]
const initialConnectors:Connector[]=[{id:'conn-1',from:{locationId:'loc-1',transitionId:'loc-1-t-25'},to:{locationId:'loc-2',transitionId:'loc-2-t-34'},color:'#fff',arrows:'none',fromSide:'right',toSide:'left'}]

function center(l:Location,t:Transition):Point{const w=l.size/COLS,h=l.size/ROWS;return{x:l.x+t.col*w+w/2,y:l.y+t.row*h+h/2}}
function edge(l:Location,t:Transition,s:Side):Point{const c=center(l,t),w=l.size/COLS,h=l.size/ROWS;return s==='left'?{x:c.x-w/2,y:c.y}:s==='right'?{x:c.x+w/2,y:c.y}:s==='top'?{x:c.x,y:c.y-h/2}:{x:c.x,y:c.y+h/2}}
function relation(a:Location,b:Location):Side{const dx=b.x+b.size/2-(a.x+a.size/2),dy=b.y+b.size/2-(a.y+a.size/2);return Math.abs(dx)>=Math.abs(dy)?(dx>=0?'right':'left'):(dy>=0?'bottom':'top')}
function sideFor(l:Location,t:Transition,p:Point,fallback:Side):Side{const c=center(l,t),dx=p.x-c.x,dy=p.y-c.y;if(Math.abs(dx)<1&&Math.abs(dy)<1)return fallback;return Math.abs(dx)>=Math.abs(dy)?(dx>=0?'right':'left'):(dy>=0?'bottom':'top')}
function boundary(l:Location,p:Point):Point{const L=l.x,R=l.x+l.size,T=l.y,B=l.y+l.size,cl=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));const q=[{x:L,y:cl(p.y,T,B),d:Math.abs(p.x-L)},{x:R,y:cl(p.y,T,B),d:Math.abs(p.x-R)},{x:cl(p.x,L,R),y:T,d:Math.abs(p.y-T)},{x:cl(p.x,L,R),y:B,d:Math.abs(p.y-B)}];return q.reduce((a,b)=>b.d<a.d?b:a,q[0])}
function defaults(a:Point,b:Point,s:Side):Point[]{if(s==='left'||s==='right'){const x=a.x+(b.x-a.x)/2;return[a,{x,y:a.y},{x,y:b.y},b]}const y=a.y+(b.y-a.y)/2;return[a,{x:a.x,y},{x:b.x,y},b]}
function same(a:Point,b:Point,t=5){return Math.hypot(a.x-b.x,a.y-b.y)<=t}
function normalize(p:Point[]):Point[]{const d=p.reduce<Point[]>((a,v)=>!a.length||!same(a[a.length-1],v)?[...a,v]:a,[]);const r:Point[]=[];d.forEach((v,i)=>{if(i>0&&i<d.length-1){const a=d[i-1],b=d[i+1],cross=Math.abs((v.x-a.x)*(b.y-a.y)-(v.y-a.y)*(b.x-a.x));if(cross<8*Math.max(1,Math.hypot(b.x-a.x,b.y-a.y))&&v.x>=Math.min(a.x,b.x)-8&&v.x<=Math.max(a.x,b.x)+8&&v.y>=Math.min(a.y,b.y)-8&&v.y<=Math.max(a.y,b.y)+8)return}r.push(v)});return r}
function route(a:Point,b:Point,s:Side,bends?:Point[]){
 const raw=bends?.length?[a,...bends,b]:defaults(a,b,s)
 if(raw.length<2)return raw
 const out:Point[]=[raw[0]]
 for(let i=1;i<raw.length;i++){
  const prev=out[out.length-1],cur=raw[i]
  if(Math.abs(cur.x-prev.x)<0.5||Math.abs(cur.y-prev.y)<0.5){out.push(cur);continue}
  out.push({x:cur.x,y:prev.y});out.push(cur)
 }
 return normalize(out)
}
function path(p:Point[]){return p.map((v,i)=>`${i?'L':'M'} ${v.x} ${v.y}`).join(' ')}
function handle(l:Location,t:Transition|undefined,s:Side):Point{if(!t)return{x:l.x+l.size/2,y:l.y+l.size/2};return edge(l,t,s)}
function nearestSide(l:Location,t:Transition,p:Point,fallback:Side):Side{
 const c=center(l,t),w=l.size/COLS,h=l.size/ROWS
 const candidates:[Side,Point][]=[['left',{x:c.x-w/2,y:c.y}],['right',{x:c.x+w/2,y:c.y}],['top',{x:c.x,y:c.y-h/2}],['bottom',{x:c.x,y:c.y+h/2}]]
 let best=fallback,bestDistance=Infinity
 for(const [side,point] of candidates){const d=Math.hypot(p.x-point.x,p.y-point.y);if(d<bestDistance){bestDistance=d;best=side}}
 return bestDistance<=MAGNET?best:fallback
}

export function App(){
 const [mode,setMode]=useState<'viewer'|'editor'>('editor'),[locations,setLocations]=useState(initialLocations),[connectors,setConnectors]=useState(initialConnectors)
 const [selected,setSelected]=useState<string|null>(null),[selectedConnector,setSelectedConnector]=useState<string|null>(null),[hovered,setHovered]=useState<Endpoint|null>(null),[hoverLoc,setHoverLoc]=useState<string|null>(null),[start,setStart]=useState<Endpoint|null>(null)
 const [zoom,setZoom]=useState(1),[snap,setSnap]=useState(true),[connectionMode,setConnectionMode]=useState(false),[deleteMode,setDeleteMode]=useState(false),[oneWay,setOneWay]=useState(false),[pan,setPan]=useState(false)
 type MidDrag={id:string;index:number;points:Point[]}
 const drag=useRef<any>(null),panDrag=useRef<any>(null),midDrag=useRef<MidDrag|null>(null),endDrag=useRef<any>(null),shellRef=useRef<HTMLElement|null>(null)
 const map=useMemo(()=>new Map(locations.map(l=>[l.id,l])),[locations])
 const connected=useMemo(()=>{const s=new Set<string>();connectors.forEach(c=>{s.add(`${c.from.locationId}:${c.from.transitionId}`);if(!c.oneWay)s.add(`${c.to.locationId}:${c.to.transitionId}`)});return s},[connectors])
 const orange=useMemo(()=>new Set(connectors.filter(c=>c.oneWay).map(c=>`${c.from.locationId}:${c.from.transitionId}`)),[connectors])
 function addLocation(){const id=`loc-${Date.now()}`;setLocations(v=>[...v,{id,name:`Локация ${v.length+1}`,x:900+v.length*100,y:1100+v.length*100,size:SIZE,background:null,transitions:makeTransitions(id)}]);setSelected(id)}
 function startDrag(e:ReactPointerEvent<SVGElement>,l:Location,allowConnection=false){if(mode!=='editor'||(!allowConnection&&connectionMode)||pan)return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:l.id,sx:e.clientX,sy:e.clientY,x:l.x,y:l.y,size:l.size};setSelected(l.id)}
 function moveLocation(e:ReactPointerEvent<SVGElement>){if(!drag.current)return;const d=drag.current;let x=d.x+(e.clientX-d.sx)/(zoom*SCALE),y=d.y+(e.clientY-d.sy)/(zoom*SCALE);if(snap){x=Math.round(x/SNAP)*SNAP;y=Math.round(y/SNAP)*SNAP}const nx=Math.max(34,Math.min(CW-d.size-34,x)),ny=Math.max(34,Math.min(CH-d.size-34,y));setLocations(v=>v.map(l=>l.id===d.id?{...l,x:nx,y:ny}:l));setConnectors(v=>v.map(c=>{
  if(c.from.locationId!==d.id&&c.to.locationId!==d.id)return c
  const fl=map.get(c.from.locationId),tl=map.get(c.to.locationId)
  const ft=fl?.transitions.find(t=>t.id===c.from.transitionId),tt=tl?.transitions.find(t=>t.id===c.to.transitionId)
  if(!fl||!tl||!ft)return {...c,bends:undefined}
  const fs=c.fromSide??sideFor(fl,ft,c.oneWay?{x:tl.x+tl.size/2,y:tl.y+tl.size/2}:tt?center(tl,tt):{x:tl.x+tl.size/2,y:tl.y+tl.size/2},relation(fl,tl))
  const ts=c.toSide??(tt?sideFor(tl,tt,center(fl,ft),relation(tl,fl)):undefined)
  return {...c,fromSide:fs,toSide:ts,bends:undefined}
}))}
 function stopDrag(e?:ReactPointerEvent<SVGElement>){if(drag.current&&e&&e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);drag.current=null}
 function beginPan(e:ReactPointerEvent<HTMLElement>){if(!pan||e.button!==0)return;const s=shellRef.current;if(!s)return;e.preventDefault();panDrag.current={sx:e.clientX,sy:e.clientY,l:s.scrollLeft,t:s.scrollTop};s.setPointerCapture(e.pointerId)}
 function movePan(e:ReactPointerEvent<HTMLElement>){const d=panDrag.current,s=shellRef.current;if(!d||!s)return;s.scrollLeft=d.l-(e.clientX-d.sx);s.scrollTop=d.t-(e.clientY-d.sy)}
 function stopPan(e?:ReactPointerEvent<HTMLElement>){const s=shellRef.current;if(s&&e&&s.hasPointerCapture(e.pointerId))s.releasePointerCapture(e.pointerId);panDrag.current=null}
 function toggleConnection(){setConnectionMode(v=>{const n=!v;if(!n){setStart(null);setDeleteMode(false);setOneWay(false)}return n})}
 function beginConnection(ep:Endpoint,e:ReactPointerEvent){if(!connectionMode||deleteMode||oneWay||mode!=='editor')return;e.stopPropagation();setStart(ep);setSelected(ep.locationId)}
 function beginOne(ep:Endpoint,e:ReactPointerEvent){if(!connectionMode||deleteMode||!oneWay||start)return;e.stopPropagation();setStart(ep);setSelected(ep.locationId)}
 function finishConnection(ep:Endpoint,e:ReactPointerEvent){if(!start||!connectionMode||deleteMode||oneWay)return;e.stopPropagation();if(start.locationId===ep.locationId&&start.transitionId===ep.transitionId)return;const fl=map.get(start.locationId),tl=map.get(ep.locationId);const ft=fl?.transitions.find(t=>t.id===start.transitionId),tt=tl?.transitions.find(t=>t.id===ep.transitionId);if(!fl||!tl||!ft||!tt)return;const fs=sideFor(fl,ft,center(tl,tt),relation(fl,tl)),ts=sideFor(tl,tt,center(fl,ft),relation(tl,fl));setConnectors(v=>[...v,{id:`conn-${Date.now()}`,from:start,to:ep,color:'#fff',arrows:'none',fromSide:fs,toSide:ts}]);setStart(null)}
 function finishOne(l:Location,e:ReactPointerEvent<SVGElement>){if(!start||!connectionMode||!oneWay||deleteMode||start.locationId===l.id)return;e.stopPropagation();const fl=map.get(start.locationId);const ft=fl?.transitions.find(t=>t.id===start.transitionId);if(!fl||!ft)return;const fs=sideFor(fl,ft,{x:l.x+l.size/2,y:l.y+l.size/2},relation(fl,l));setConnectors(v=>[...v,{id:`conn-${Date.now()}`,from:start,to:{locationId:l.id,transitionId:'__location__'},color:'#FF7000',arrows:'none',oneWay:true,fromSide:fs}]);setStart(null);setHoverLoc(null)}
 function deleteTransition(ep:Endpoint,e:ReactPointerEvent){if(!deleteMode)return;e.stopPropagation();setConnectors(v=>v.filter(c=>!(c.from.locationId===ep.locationId&&c.from.transitionId===ep.transitionId)&&!(c.to.locationId===ep.locationId&&c.to.transitionId===ep.transitionId)));setStart(null)}
 function deleteSelected(){if(!selected)return;setLocations(v=>v.filter(l=>l.id!==selected));setConnectors(v=>v.filter(c=>c.from.locationId!==selected&&c.to.locationId!==selected));setSelected(null);setSelectedConnector(null)}
 function svgPoint(e:ReactPointerEvent<SVGElement>):Point{const svg=e.currentTarget.ownerSVGElement,r=svg?.getBoundingClientRect();return r?{x:(e.clientX-r.left)/(SCALE*zoom),y:(e.clientY-r.top)/(SCALE*zoom)}:{x:0,y:0}}
 function geometry(c:Connector){const fl=map.get(c.from.locationId),tl=map.get(c.to.locationId);if(!fl||!tl)return null;const ft=fl.transitions.find(t=>t.id===c.from.transitionId);if(!ft)return null;const tt=tl.transitions.find(t=>t.id===c.to.transitionId),tc=c.oneWay?{x:tl.x+tl.size/2,y:tl.y+tl.size/2}:tt?center(tl,tt):{x:tl.x+tl.size/2,y:tl.y+tl.size/2},fs=c.fromSide??sideFor(fl,ft,tc,relation(fl,tl)),ts=c.toSide??(tt?sideFor(tl,tt,center(fl,ft),relation(tl,fl)):relation(tl,fl)),a=edge(fl,ft,fs),b=c.oneWay?boundary(tl,a):tt?edge(tl,tt,ts):a;return{fl,tl,ft,tt,fs,ts,a,b}}
 function beginMid(e:ReactPointerEvent<SVGCircleElement>,id:string,index:number){if(mode!=='editor'||connectionMode||pan||deleteMode)return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);const c=connectors.find(v=>v.id===id),g=c&&geometry(c);if(!c||!g)return;midDrag.current={id,index,points:route(g.a,g.b,g.fs,c.bends)};setSelectedConnector(id)}
 function dragMid(e:ReactPointerEvent<SVGCircleElement>){const d=midDrag.current;if(!d)return;const i=d.index,p=d.points;if(!p[i]||!p[i+1])return;const q=svgPoint(e),next=p.map(v=>({...v})),horizontal=Math.abs(p[i+1].x-p[i].x)>=Math.abs(p[i+1].y-p[i].y),last=p.length-2
  if(i>0&&i<last){if(horizontal){next[i].y=q.y;next[i+1].y=q.y}else{next[i].x=q.x;next[i+1].x=q.x}}
  else if(i===0){if(horizontal){next.splice(1,0,{x:p[0].x,y:q.y});next[2].y=q.y}else{next.splice(1,0,{x:q.x,y:p[0].y});next[2].x=q.x}}
  else {if(horizontal){next.splice(next.length-1,0,{x:p[last].x,y:q.y});next[next.length-2].y=q.y}else{next.splice(next.length-1,0,{x:q.x,y:p[last].y});next[next.length-2].x=q.x}}
  const c=connectors.find(v=>v.id===d.id),g=c&&geometry(c);if(!c||!g)return;const nr=normalize(next),def=defaults(g.a,g.b,g.fs),reset=nr.length===def.length&&nr.every((v,j)=>same(v,def[j],8));setConnectors(v=>v.map(x=>x.id===d.id?{...x,bends:reset?undefined:nr.slice(1,-1)}:x))
 }
 function stopMid(e?:ReactPointerEvent<SVGCircleElement>){if(e&&e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);midDrag.current=null}
 function beginEnd(e:ReactPointerEvent<SVGCircleElement>,id:string,which:'from'|'to'){if(mode!=='editor'||connectionMode||pan||deleteMode)return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);endDrag.current={id,which};setSelectedConnector(id)}
 function dragEnd(e:ReactPointerEvent<SVGCircleElement>){const d=endDrag.current;if(!d)return;const c=connectors.find(v=>v.id===d.id),g=c&&geometry(c);if(!c||!g)return;const l=d.which==='from'?g.fl:g.tl,t=d.which==='from'?g.ft:g.tt;if(!t)return;const p=svgPoint(e),fallback=d.which==='from'?(c.fromSide??g.fs):(c.toSide??g.ts),s=nearestSide(l,t,p,fallback);if(s===fallback)return;setConnectors(v=>v.map(x=>x.id===d.id?{...x,[d.which==='from'?'fromSide':'toSide']:s,bends:undefined}:x))}
 function stopEnd(e?:ReactPointerEvent<SVGCircleElement>){if(e&&e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);endDrag.current=null}
 function setBackground(file:File|undefined){if(!file||!selected)return;const r=new FileReader();r.onload=()=>setLocations(v=>v.map(l=>l.id===selected?{...l,background:String(r.result)}:l));r.readAsDataURL(file)}
 function removeBackground(){if(selected)setLocations(v=>v.map(l=>l.id===selected?{...l,background:null}:l))}
 const titleFontSize=50,titleHitbox=16
 return <div className="app">
  <header className="topbar"><div className="brand">KARTA-CATWAR</div><div className="mode-switch"><button className={mode==='viewer'?'active':''} onClick={()=>{setMode('viewer');setConnectionMode(false);setDeleteMode(false);setOneWay(false);setStart(null);setSelectedConnector(null)}}>Просмотр</button><button className={mode==='editor'?'active':''} onClick={()=>setMode('editor')}>Редактор</button></div><div className="top-actions"><button onClick={()=>setZoom(v=>Math.max(.4,v-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(v=>Math.min(2,v+.1))}>+</button></div></header>
  <aside className="toolbar"><button title="Выбор" className={!pan&&!connectionMode?'active-tool':''} onClick={()=>{setPan(false);setConnectionMode(false);setDeleteMode(false);setOneWay(false);setStart(null);setSelectedConnector(null)}}><img src="/KARTA-CATWAR/icons/cursor.svg" alt=""/></button><button title="Перемещение по холсту" className={pan?'active-tool':''} onClick={()=>{setPan(v=>!v);setStart(null);setSelectedConnector(null)}}><img src="/KARTA-CATWAR/icons/holding-hand.svg" alt=""/></button>{mode==='editor'&&<><button title="Привязка к сетке" className={snap?'active-tool':''} onClick={()=>setSnap(v=>!v)}><img src="/KARTA-CATWAR/icons/grid.svg" alt=""/></button><button title="Режим переходов" className={connectionMode?'active-tool':''} onClick={toggleConnection}><img src="/KARTA-CATWAR/icons/arrow.svg" alt=""/></button><button title="Добавить локацию" onClick={addLocation}><img src="/KARTA-CATWAR/icons/add-location.svg" alt=""/></button><button title="Удалить выбранное" onClick={deleteSelected}><img src="/KARTA-CATWAR/icons/delete-location.svg" alt=""/></button></>}</aside>
  {mode==='editor'&&connectionMode&&<aside className="transition-tools"><button title="Переход в одну сторону" className={oneWay?'active-tool':''} onClick={()=>{setOneWay(v=>!v);setDeleteMode(false);setStart(null)}}><img src="/KARTA-CATWAR/icons/arrow.svg" alt=""/></button><button title="Удаление переходов" className={deleteMode?'active-tool':''} onClick={()=>{setDeleteMode(v=>!v);setOneWay(false);setStart(null)}}><img src="/KARTA-CATWAR/icons/delete-location.svg" alt=""/></button></aside>}
  <main ref={shellRef} className={`canvas-shell ${pan?'pan-mode':''}`} onPointerDown={beginPan} onPointerMove={movePan} onPointerUp={stopPan} onPointerCancel={stopPan}><div className="canvas" onClick={e=>{if(e.target===e.currentTarget&&!pan){setSelected(null);setStart(null);setSelectedConnector(null)}}}><svg className="map" width={CW} height={CH} viewBox={`0 0 ${CW} ${CH}`} style={{transform:`scale(${SCALE*zoom})`}}>
   <defs><pattern id="canvas-grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M 32 0 L 0 0 0 32" fill="none" stroke="#20252d" strokeWidth="1"/></pattern></defs><rect width={CW} height={CH} fill="url(#canvas-grid)"/>
   {locations.map(l=><g key={l.id} className={`location ${selected===l.id?'selected':''}`} transform={`translate(${l.x} ${l.y})`}>
    <rect width={l.size} height={l.size} className="location-bg" onPointerDown={e=>{if(start&&oneWay)finishOne(l,e);else startDrag(e,l)}} onPointerMove={moveLocation} onPointerUp={stopDrag} onPointerCancel={()=>stopDrag()} onClick={e=>{e.stopPropagation();setSelected(l.id)}} onPointerEnter={()=>setHoverLoc(l.id)} onPointerLeave={()=>setHoverLoc(null)}/>{l.background&&<image href={l.background} x="0" y="0" width={l.size} height={l.size} preserveAspectRatio="xMidYMid slice" pointerEvents="none"/>}
    <rect x={-titleHitbox} y={-titleFontSize-titleHitbox} width={l.size+titleHitbox*2} height={titleFontSize+titleHitbox+20} className="location-title-hitbox" onPointerDown={e=>startDrag(e,l,true)} onPointerMove={moveLocation} onPointerUp={stopDrag} onPointerCancel={()=>stopDrag()} onClick={e=>{e.stopPropagation();setSelected(l.id)}}/><text x={l.size/2} y="-14" textAnchor="middle" className="location-title" style={{fontSize:titleFontSize}} pointerEvents="none">{l.name}</text>
    <g className="transition-grid" pointerEvents={connectionMode&&!(oneWay&&start)?'auto':'none'}>{l.transitions.map(t=>{const w=l.size/COLS,h=l.size/ROWS,ep={locationId:l.id,transitionId:t.id},key=`${l.id}:${t.id}`,st=start?.locationId===l.id&&start.transitionId===t.id,c=connected.has(key),o=orange.has(key);return <g key={t.id} className="transition-cell" onPointerEnter={()=>setHovered(ep)} onPointerLeave={()=>setHovered(null)} onPointerDown={e=>{e.stopPropagation();setSelected(l.id);if(deleteMode)deleteTransition(ep,e);else if(start)finishConnection(ep,e);else if(oneWay)beginOne(ep,e);else beginConnection(ep,e)}} onClick={e=>e.stopPropagation()}><rect x={t.col*w} y={t.row*h} width={w} height={h} style={{fill:st?(oneWay?'#FF7000':'#ffffff38'):o?'#FF7000':c?'#fff':'transparent',stroke:o||(st&&oneWay)?'#FF7000':'rgba(255,255,255,.15)',strokeWidth:2}}/></g>})}</g><rect width={l.size} height={l.size} className="location-frame" pointerEvents="none"/>
   </g>)}
   <g className="connectors-layer">{connectors.map(c=>{const g=geometry(c);if(!g)return null;const pts=route(g.a,g.b,g.fs,c.bends),d=path(pts),edit=mode==='editor'&&selectedConnector===c.id,handles=pts.slice(0,-1).map((p,i)=>({p:{x:(p.x+pts[i+1].x)/2,y:(p.y+pts[i+1].y)/2},i})),sides:Side[]=['left','right','top','bottom'];return <g key={c.id}><path d={d} fill="none" stroke="transparent" strokeWidth="22" pointerEvents="stroke" onPointerDown={e=>{if(connectionMode||pan||deleteMode)return;e.stopPropagation();setSelectedConnector(c.id)}}/>{c.oneWay?<path d={d} fill="none" stroke="#FF7000" strokeWidth="4" strokeDasharray="10 8" strokeLinecap="butt" strokeLinejoin="miter" pointerEvents="none"/>:<><path d={d} fill="none" stroke="#000" strokeWidth="7" strokeLinecap="butt" strokeLinejoin="miter" pointerEvents="none"/><path d={d} fill="none" stroke="#fff" strokeWidth="4" strokeLinecap="butt" strokeLinejoin="miter" pointerEvents="none"/></>}{edit&&<>{handles.map(({p,i})=><circle key={`m${i}`} className="connector-mid-handle" cx={p.x} cy={p.y} r="10" onPointerDown={e=>beginMid(e,c.id,i)} onPointerMove={dragMid} onPointerUp={stopMid} onPointerCancel={()=>stopMid()}/>)}{sides.map(s=>{const p=handle(g.fl,g.ft,s);return <g key={`f${s}`} className="connector-side-handle-group"><circle cx={p.x} cy={p.y} r="26" fill="transparent" pointerEvents="all" onPointerDown={e=>beginEnd(e,c.id,'from')} onPointerMove={dragEnd} onPointerUp={stopEnd} onPointerCancel={()=>stopEnd()}/><circle className={`connector-side-handle ${c.fromSide===s?'active':''}`} cx={p.x} cy={p.y} r="13" pointerEvents="none"/></g>})}{!c.oneWay&&g.tt&&sides.map(s=>{const p=handle(g.tl,g.tt,s);return <g key={`t${s}`} className="connector-side-handle-group"><circle cx={p.x} cy={p.y} r="26" fill="transparent" pointerEvents="all" onPointerDown={e=>beginEnd(e,c.id,'to')} onPointerMove={dragEnd} onPointerUp={stopEnd} onPointerCancel={()=>stopEnd()}/><circle className={`connector-side-handle ${c.toSide===s?'active':''}`} cx={p.x} cy={p.y} r="13" pointerEvents="none"/></g>})}</>}</g>})}</g>
   {start&&!deleteMode&&!oneWay&&hovered&&(()=>{const fl=map.get(start.locationId),tl=map.get(hovered.locationId);if(!fl||!tl)return null;const ft=fl.transitions.find(t=>t.id===start.transitionId),tt=tl.transitions.find(t=>t.id===hovered.transitionId);if(!ft||!tt)return null;const fs=sideFor(fl,ft,center(tl,tt),relation(fl,tl)),a=edge(fl,ft,fs),b=edge(tl,tt,sideFor(tl,tt,center(fl,ft),relation(tl,fl))),d=path(defaults(a,b,fs));return <g><path d={d} fill="none" stroke="#000" strokeWidth="7"/><path d={d} fill="none" stroke="#fff" strokeWidth="4"/></g>})()}
   {start&&oneWay&&!deleteMode&&hoverLoc&&(()=>{const fl=map.get(start.locationId),tl=map.get(hoverLoc);if(!fl||!tl||fl.id===tl.id)return null;const ft=fl.transitions.find(t=>t.id===start.transitionId);if(!ft)return null;const fs=sideFor(fl,ft,{x:tl.x+tl.size/2,y:tl.y+tl.size/2},relation(fl,tl)),a=edge(fl,ft,fs),b=boundary(tl,a),d=path(defaults(a,b,fs));return <path d={d} fill="none" stroke="#FF7000" strokeWidth="4" strokeDasharray="10 8"/>})()}
  </svg></div></main>
  {selected&&mode==='editor'&&<section className="inspector"><div className="inspector-title">Локация</div><input value={map.get(selected)?.name??''} onChange={e=>setLocations(v=>v.map(l=>l.id===selected?{...l,name:e.target.value}:l))}/><div className="inspector-field"><label>Фон локации</label><input type="file" accept="image/*" onChange={e=>setBackground(e.target.files?.[0])}/>{map.get(selected)?.background&&<button className="remove-bg" onClick={removeBackground}>Убрать фон</button>}</div><div className="inspector-note">Фон находится под сеткой переходов.</div></section>}
 </div>
}
